### ISSUE TITLE
Suggestion: Multiple People/Items per letter

### ISSUE THREAD

**Issue by adammead** [mmeadx/meadABCs#3]
Oliver and Malcolm call Grandma Pat Nana and Grandma Jacki Grandma JJ. What if G was Grandma JJ, Grandpa (Terry), and Grandpa (Howard)? Malcolm and Oliver could be on M and O as well.

**Comment by mmeadx** [comment]
Working on updating with my voice actor later! Fixed the issue where the sound keeps playing if you hit a new letter.
